<!-- ====================================================================== -->
<!-- ****************************            ****************************** --> 
<!-- ****************************BEGIN TABLES****************************** --> 
<!-- ****************************             ***************************** --> 
<!-- ======================================================================--> 

\FloatBarrier

<!-- ********************************************************************** --> 
<!-- *********************Commercial landings TABLES*********************** --> 
<!-- ********************************************************************** --> 
```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
     Comm_removal = read.csv("./txt_files/Comm_removals.csv")
     colnames(Comm_removal) = c('Year',
                                'Hook-and-line (plus pot and other)',
                                'Trawl',
                                'Gillnet',
                                'Mexico',
                                'Total U.S. Commercial Removals',
                                'Source')
```

```{r, results='asis'}
   Comm_removal.table = xtable(Comm_removal, 
                    caption = c("Commercial landings (mt) from the commercial 
                                fisheries. Data sources are the CDFG Fishery
                                Bulletins (available from California Explores the Ocean)
                                and the California Fisheries Information System (CFIS).")
                    #,label="tab:CommCatches"
                    )
   align(Comm_removal.table) =c('l','c', 
                            '>{\\centering}p{1in}',
                            '>{\\centering}p{.6in}',
                            '>{\\centering}p{.6in}',
                            '>{\\centering}p{.6in}',
                            '>{\\centering}p{1in}',
                            'l')  
     print(Comm_removal.table,include.rownames=FALSE,      
           caption.placement="top",align=TRUE,tabular.environment="longtable",
            floating=FALSE,  #sanitize.text.function = function(x){x},
           add.to.row = list(pos = list(0),command = 
                        paste("\\hline  \\endfirsthead",  # First caption
                                "\\caption[]{Commercial landings (mt) from the commercial 
                                fisheries. Data sources are the CDFG Fishery
                                Bulletins (available from California Explores the Ocean)
                                and the California Fisheries Information System (CFIS).} \\label{tab:CommCatches} \\\\ \\hline", # Addit. captions
                                paste(colnames(Comm_removal)[1], paste("&", colnames(Comm_removal)[2:7], collapse=" ")), # Column names
                                "\\\\ \\hline ",
                                "\\endhead", 
                                "\\hline \\multicolumn{6}{l}{\\textit{Continues next page}} \\ 
                                 \\endfoot
                                 \\endlastfoot",collapse=" ")))
```


```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
## Length comp sample size tables
    ComHL_length = read.csv('./txt_files/Fleet1_ComHL_lengthsamplesize.csv')
   ComNet_length = read.csv('./txt_files/Fleet2_ComNet_lengthsamplesize.csv')
   ComTrawl_length = read.csv('./txt_files/Fleet3_ComTrawl_lengthsamplesize.csv')
     column_names = c('Year',
                      'Fish',
                      'Trips',
                      'Sample size',
                      'Mean length (cm)')
     
   colnames(ComHL_length) = column_names
   colnames(ComNet_length) = column_names
   colnames(ComTrawl_length) = column_names

```

\FloatBarrier

```{r, results='asis'}
    ComHL_length.table = xtable(ComHL_length,
                                caption = c('The annual number of California scorpionfish 
                                              sampled from the the commercial hook-and-line 
                                            fleet for lengths. Sample size is calculated 
                                            using Stewart’s method (see text for detail)'),
                                label='tab:ComHL_lengthsample',
                                digits=c(0,0,0,0,2,0))
cat('\\vspace{2in}')
      print(ComHL_length.table,
            include.rownames=FALSE,      
            caption.placement="top")
   ##gillnet   
     ComNet_length.table = xtable(ComNet_length,
                                caption = c('The annual number of California scorpionfish 
                                              sampled from the the commercial gillnet 
                                            fleet for lengths. Sample size is calculated 
                                            using Stewart’s method (see text for detail)'),
                                label='tab:ComNet_lengthsample',
                                digits=c(0,0,0,0,2,0))
cat('\\vspace{2in}')
     
      print(ComNet_length.table,
            include.rownames=FALSE,      
            caption.placement="top")
      
      
    ##trawl
      ComTrawl_length.table = xtable(ComTrawl_length,
                                caption = c('The annual number of California scorpionfish 
                                              sampled from the the commercial trawl 
                                            fleet for lengths. Sample size is calculated 
                                            using Stewart’s method (see text for detail)'),
                                label='tab:ComTrawl_lengthsample',
                                digits=c(0,0,0,0,2,0))
cat('\\vspace{2in}')

      print(ComTrawl_length.table,
            include.rownames=FALSE,      
            caption.placement="top")


```




\FloatBarrier
\newpage
<!-- ********************************************************************** --> 
<!-- ***********Recreational Landings and discards TABLE******************* --> 
<!-- ********************************************************************** --> 
<!-- Washington rec removal TABLES--> 
```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
     Rec_removal = read.csv("./txt_files/Rec_removals.csv")
     colnames(Rec_removal) = c('Year',
                                  'Private',
                                  'Party/charter',
                                  'Dead Discard (all modes)',
                                  'Total Removals')
```
```{r, results='asis'}
   Rec_removal.table = xtable(Rec_removal, 
                          caption = c("Recreational removals (mt) from the party/charter 
                                        and private vessels. Removals from man-made and 
                                        beach/bank modes were included in the private mode
                                        removals. Dead discards include all modes. CDFW provided 
                                        all data. Note: A discard mortality rate of seven percent 
                                        was applied 
                                        to the dead discard removals.")
                        #  ,label="tab:Rec_removal"
                          )
    align(Rec_removal.table) = 'lccccc'

cat('\\vspace{2in}')      
    print(Rec_removal.table, include.rownames=FALSE,      
           caption.placement="top",align=TRUE,tabular.environment="longtable",
            floating=FALSE,  #sanitize.text.function = function(x){x},
           add.to.row = list(pos = list(0),command = 
                        paste("\\hline  \\endfirsthead",  # First caption
                                "\\caption[]{Recreational removals (mt) from the party/charter 
                                        and private vessels. Removals from man-made and 
                                        beach/bank modes were included in the private mode
                                        removals. Dead discards include all modes. CDFW provided 
                                        all data. Note: A discard mortality rate of seven percent 
                                        was applied 
                                        to the dead discard removals.} \\label{tab:Rec_removal} \\\\ \\hline", # Addit. captions
                                paste(colnames(Rec_removal)[1], paste("&", colnames(Rec_removal)[2:5], collapse=" ")), # Column names
                                "\\\\ \\hline ",
                                "\\endhead", 
                                "\\hline \\multicolumn{5}{l}{\\textit{Continues next page}} \\ 
                                 \\endfoot
                                 \\endlastfoot",collapse=" ")))

```

\newpage
\FloatBarrier
<!-- ********************************************************************** --> 
<!-- ***********Fleet 4 Recreational PR dockside survey TABLES************* --> 
<!-- ********************************************************************** --> 


```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
      ##read in data for 3 tables
        Fleet4_filter = read.csv("./txt_files/Fleet4_RecPR_dockside_filter.csv")
        Fleet4_aic = read.csv("./txt_files/Fleet4_RecPR_dockside_aic.csv")
        Fleet4_index = read.csv("./txt_files/Fleet4_RecPR_dockside_index.csv")
        Fleet4_length = read.csv('./txt_files/Fleet4_RecPR_lengthsamplesize.csv')

        colnames(Fleet4_filter) = c('Filter',
                                    'Criteria',
                                    'Sample size (no. positive trips)',
                                    'Sample size (no. of trips)')
        
        colnames(Fleet4_aic) = c('Model',
                                 'Binomial',
                                 'Lognormal')
        
        colnames(Fleet4_index) = c('Year',
                                   'Index',
                                   'Log-scale SE')
      
        column_names = c('Year',
                         'Fish',
                         'Trips',
                         'Sample size',
                         'Mean length (cm)')

```
```{r, results='asis'}
    #Fleet 4 filter
         Fleet4_filter.table = xtable(Fleet4_filter,
                              caption = c("Recreational private mode dockside data sample 
                                          sizes at each data filtering step.  
                                          The bold value indicates the final sample size 
                                          used for delta-GLM analysis."),
                              label='tab:Fleet4_RecPR_dockside_filter',
                              digits=0)
        
        align(Fleet4_filter.table) = c('l',
                                  '>{\\raggedright}p{1.5in}',
                                  '>{\\raggedright}p{2.6in}',
                                  '>{\\raggedright}p{1in}',
                                  '>{\\raggedright}p{1in}')          
        
        print(Fleet4_filter.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 4 aic
         Fleet4_aic.table = xtable(Fleet4_aic,
                              caption = c("AIC values for each model in the
                                          recreational private mode dockside sample 
                                          index."),
                              label='tab:Fleet4_RecPR_dockside_aic',
                              digits=0)
        
cat('\\vspace{3in}')        

        print(Fleet4_aic.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 4 index
         Fleet4_index.table = xtable(Fleet4_index,
                              caption = c("The recreational private mode 
                                            dockside sample index."),
                              digits=4,
                              label='tab:Fleet4_RecPR_dockside_index')
        
cat('\\vspace{3in}')  

        print(Fleet4_index.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})
        
  #Fleet 4 length sample size
       Fleet4_length.table = xtable(Fleet4_length,
                                caption = c('The annual number of California scorpionfish 
                                              sampled from the the recreational private 
                                              mode fleet for lengths. Data from 1980-2003
                                            were downloaded from RecFIN and from CDFW for
                                            2004-2016. The number of trips is the number
                                            of unique ID Codes from 1980-2003 and the 
                                            number of trips from 2004-2016.'),
                                label='tab:Fleet4_lengthsample')

      print(Fleet4_length.table,
            include.rownames=FALSE,      
            caption.placement="top")
```

\FloatBarrier
<!-- ********************************************************************** -->
<!-- ************Fleet 5 Recreational CPFV logbook index TABLES************ -->
<!-- ********************************************************************** -->
```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
      ##read in data for 3 tables
        Fleet5_filter = read.csv("./txt_files/Fleet5_RecPC_CPFVlogbook_filter.csv")
        Fleet5_aic = read.csv("./txt_files/Fleet5_RecPC_CPFVlogbook_aic.csv")
        Fleet5_index = read.csv("./txt_files/Fleet5_RecPC_CPFVlogbook_index.csv")
        
        colnames(Fleet5_filter) = c('Filter',
                                    'Criteria',
                                    'Sample size (no. of trips)')
        
        colnames(Fleet5_aic) = c('Model',
                                 'Negative Binomial')
        
        colnames(Fleet5_index)= c('Year',
                                  'Index',
                                  'Log-scale SE')

```
```{r, results='asis'}
    #Fleet 5 filter
         Fleet5_filter.table = xtable(Fleet5_filter,
                              caption = c("Recreational CPFV logbook sample 
                                          sizes at each data filtering step.  
                                          The bold value indicates the final sample size 
                                          used for index analysis."),
                              label='tab:Fleet5_RecPC_CPFVlogbook_filter')
        
        align(Fleet5_filter.table) = c('l',
                                  '>{\\raggedright}p{1.5in}',
                                  '>{\\raggedright}p{3in}',
                                  '>{\\raggedright}p{1in}')          
        
        print(Fleet5_filter.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

        cat('\\newpage')  
        
   #Fleet 5 aic
         Fleet5_aic.table = xtable(Fleet5_aic,
                              caption = c("AIC values for each model in the
                                          recreational CPFV logbook sample 
                                          index."),
                              label='tab:Fleet5_RecPC_CPFVlogbook_aic')
        
        
        print(Fleet5_aic.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 5 index
         Fleet5_index.table = xtable(Fleet5_index,
                              digits=4,
                              caption = c("The recreational CPFV  
                                            logbook sample index."),
                              label='tab:Fleet5_RecPC_CPFVlogbook_index')
        
 cat('\\vspace{2in}')       
        print(Fleet5_index.table, 
              include.rownames=FALSE,
              caption.placement="top",
              sanitize.text.function = function(x){x},
              scalebox=.9)
```

\FloatBarrier
<!-- ********************************************************************** -->
<!-- ************Fleet 5 Recreational PC dockside index TABLES************* -->
<!-- ********************************************************************** -->
```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
      ##read in data for 3 tables
        Fleet5a_filter = read.csv("./txt_files/Fleet5_RecPC_dockside_filter.csv")
        Fleet5a_aic = read.csv("./txt_files/Fleet5_RecPC_dockside_aic.csv")
        Fleet5_length = read.csv('./txt_files/Fleet5_RecPC_lengthsamplesize.csv')
        
        colnames(Fleet5a_filter) = c('Filter',
                                    'Criteria',
                                    'Sample size (no. of trips)')
        
        colnames(Fleet5a_aic) = c('Model',
                                 'Binomial',
                                 'Lognormal')
        

        colnames(Fleet5_length) = c('Year',
                                    'Fish',
                                    'Trips',
                                    'Mean length (cm)',
                                    'Source')
```
```{r, results='asis'}
    #Fleet 5a filter
         Fleet5a_filter.table = xtable(Fleet5a_filter,
                              caption = c("Recreational CPFV dockside sample 
                                          sizes at each data filtering step.  
                                          The bold value indicates the final sample size 
                                          used for delta-GLM analysis."),
                              label='tab:Fleet5_RecPC_dockside_filter')
        
        align(Fleet5a_filter.table) = c('l',
                                  '>{\\raggedright}p{1.5in}',
                                  '>{\\raggedright}p{3in}',
                                  '>{\\raggedright}p{1in}')          
        
        print(Fleet5a_filter.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

        cat('\\vspace{2in}')
   #Fleet 5 aic
         Fleet5a_aic.table = xtable(Fleet5a_aic,
                              caption = c("AIC values for each model in the
                                          recreational CPFV logbook sample 
                                          index, including all positive trips 
                                          and false positive trips selected 
                                          with a Stephens-MacCall filter 
                                          threshold encounter probability of 0.1."),
                              label='tab:Fleet5_RecPC_dockside_aic')
        
        
        print(Fleet5a_aic.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

     #Fleet 5 length sample size
       Fleet5_length.table = xtable(Fleet5_length,
                                caption = c('The annual number of retained California scorpionfish 
                                              sampled from the the recreational party/charter 
                                              mode fleet for lengths. Length measurements
                                            from 1980-1983 and 1993-2016 were downloaded from RecFIN.  
                                            Length measurements from 1984-1989 were from an onboard
                                            observer program that measured both retained and discarded
                                            fish.'),
                                label='tab:Fleet5_lengthsample',
                                digits=0)

      print(Fleet5_length.table,
            include.rownames=FALSE,      
            caption.placement="top")   
        
        
        
```










\FloatBarrier
<!-- ********************************************************************** -->
<!-- *****Fleets 6 and 12 Recreational onboard observer index TABLES******* -->
<!-- ********************************************************************** -->


```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
      ##read in data for 3 tables
        Fleet6_filter = read.csv("./txt_files/Fleets6_12_onboard_filter.csv")
        Fleet6_aic = read.csv("./txt_files/Fleet6_RecDD_onboard_aic.csv")
        Fleet6_index = read.csv("./txt_files/Fleet6_RecDD_onboard_index.csv")
        Fleet12_aic = read.csv("./txt_files/Fleet12_RecPC_onboard_aic.csv")
        Fleet12_index = read.csv("./txt_files/Fleet12_RecPC_onboard_index.csv")
        Fleet6_length = read.csv('./txt_files/Fleet6_RecDD_lengthsamplesize.csv')
        
        colnames(Fleet6_filter) = c('Filter',
                                    'Criteria',
                                    'Sample size (no. positive drifts)',
                                    'Sample size (no. of drifts)')
        
        colnames(Fleet6_aic) = c('Model',
                                 'Binomial',
                                 'Lognormal')
        
        colnames(Fleet6_index) = c('Year',
                                   'Index',
                                   'Log-scale SE')
        
        colnames(Fleet6_length) = c('Year',
                                    'Fish',
                                    'Trips',
                                    'Mean length (cm)',
                                    'Source')
      
        colnames(Fleet12_aic) = c('Model',
                                 'Binomial',
                                 'Lognormal')
        
        colnames(Fleet12_index) = c('Year',
                                   'Index',
                                   'Log-scale SE')

```

```{r, results='asis'}
    #Fleet 6 and 12 filter
         Fleet6_filter.table = xtable(Fleet6_filter,
                              caption = c("Recreational onboard observer data sample 
                                          sizes at each data filtering step.  
                                          The bold value indicates the final sample size 
                                          used for delta-GLM analysis.
                                          The same sample data were used for the discard-only
                                          index and the retained-only catch indices"),
                              label='tab:Fleet6_RecDD_onboard_filter')
        
        align(Fleet6_filter.table) = c('l',
                                  '>{\\raggedright}p{1.5in}',
                                  '>{\\raggedright}p{2.6in}',
                                  '>{\\raggedright}p{1in}',
                                  '>{\\raggedright}p{1in}')          
        
        print(Fleet6_filter.table, 
              include.rownames=FALSE, 
              caption.placement="top",
             # tabular.environment="tabularx",
              sanitize.text.function = function(x){x})

   #Fleet 6 aic
         Fleet6_aic.table = xtable(Fleet6_aic,
                              caption = c("AIC values for each model in the
                                          recreational CPFV onboard 
                                          observer discard-only catch 
                                          index."),
                              label='tab:Fleet6_RecDD_onboard_aic')
        
        
        print(Fleet6_aic.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 6 index
         Fleet6_index.table = xtable(Fleet6_index,
                              caption = c("The recreational CPFV
                                            onboard observer discard-only
                                            catch sample index."),
                              digits=4,
                              label='tab:Fleet6_RecDD_onboard_index')
        
        
        print(Fleet6_index.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})
        
 
     #Fleet 6 length sample size
       Fleet6_length.table = xtable(Fleet6_length,
                                caption = c('The annual number of discarded California scorpionfish 
                                              sampled from the the recreational party/charter 
                                              mode fleet for lengths. Length measurements
                                            from 2003-2016 were provided by CDFW.  
                                            Length measurements from 1984-1989 were from an onboard
                                            observer program that measured both retained and discarded
                                            fish.'),
                                label='tab:Fleet6_lengthsample',
                                digits=0)

      print(Fleet6_length.table,
            include.rownames=FALSE,      
            caption.placement="top")   
        
        
               
  #Fleet 12 aic
         Fleet12_aic.table = xtable(Fleet12_aic,
                              caption = c("The AIC values for each model in the
                                          The recreational CPFV onboard 
                                          observer retained-only catch 
                                          index."),
                              label='tab:Fleet12_RecPC_onboard_aic')
        
        
        print(Fleet12_aic.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 12 index
         Fleet12_index.table = xtable(Fleet12_index,
                              caption = c("The recreational CPFV
                                            onboard observer retained-only
                                            catch sample index."),
                              digits=4,
                              label='tab:Fleet12_RecPC_onboard_index')
        
 cat('\\vspace{2in}')       
        print(Fleet12_index.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              digits=4,
              sanitize.text.function = function(x){x})
```


\FloatBarrier
<!-- ********************************************************************** -->
<!-- ***************Fleet 7 Sanitation index TABLES************************ -->
<!-- ********************************************************************** -->
```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
      ##read in data for 3 tables
        Fleet7_filter = read.csv("./txt_files/Fleet7_Sanitation_filter.csv")
        Fleet7_aic = read.csv("./txt_files/Fleet7_Sanitation_aic.csv")
        Fleet7_index = read.csv("./txt_files/Fleet7_Sanitation_index.csv")
        Fleet7_lengthdepth = read.csv("./txt_files/Fleet7_Sanitation_lengthbydepth.csv")
        Fleet7_lengthsample = read.csv("./txt_files/Fleet7_Sanitation_lengthsamplesize.csv")
        
        
        colnames(Fleet7_filter) = c('Filter',
                                    'Criteria',
                                    'City of LA',
                                    'LA County',
                                    'Orange County',
                                    'City of San Diego',
                                    'Total trawls')
        
        colnames(Fleet7_aic) = c('Model',
                                 'Binomial',
                                 'Lognormal')
        
        colnames(Fleet7_index) = c('Year',
                                   'Index',
                                   'Log-scale SE')
      
        colnames(Fleet7_lengthsample) = c('Year',
                                         'Fish',
                                         'Trips',
                                         'Mean length')
                                    
       colnames(Fleet7_lengthdepth) = c('Program',
                                         '0-24 m',
                                         '25-49 m',
                                         '50-74 m',
                                         '100+ m',
                                         'Total')


```

```{r, results='asis'}
    #Fleet 7 filter
         Fleet7_filter.table = xtable(Fleet7_filter,
                              caption = c("The trawl sample sizes for each
                                          Publicly Owned Treatment Works 
                                          trawl survey data at each data filtering step.  
                                          The bold value indicates the final sample size 
                                          used for delta-GLM analysis."),
                              label='tab:Fleet7_Sanitation_filter')
        
        align(Fleet7_filter.table) = c('l',
                                  '>{\\raggedright}p{.8in}',
                                  '>{\\raggedright}p{2in}',
                                  '>{\\raggedright}p{.6in}',
                                  '>{\\raggedright}p{.6in}',
                                  '>{\\raggedright}p{.6in}',
                                  '>{\\raggedright}p{.8in}',
                                  '>{\\raggedright}p{.6in}')          
 cat('\\vspace{2in}')       
        print(Fleet7_filter.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 7 aic
         Fleet7_aic.table = xtable(Fleet7_aic,
                              caption = c("AIC values for each model in the
                                         Publicly Owned Treatment Works trawl sample 
                                          index."),
                              label='tab:Fleet7_Sanitation_aic')
        
cat('\\vspace{2in}')        
        print(Fleet7_aic.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 7 index
         Fleet7_index.table = xtable(Fleet7_index,
                              caption = c("The Publicly Owned Treatment Works 
                                           trawl sample index."),
                              digits=4,
                              label='tab:Fleet7_Sanitation_index')
        
 cat('\\vspace{2in}')       
        print(Fleet7_index.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x},
              scalebox=.75)


  ##Fleet 7 length tables
        
Fleet7_lengthdepth.table = xtable(Fleet7_lengthdepth,
                                  caption = c("Number of fish measured by 25 m 
                                              depth bin and Publicly Owned Treatment Works program."),
                                  label = 'tab:Fleet7_lengthdepth')

Fleet7_lengthsample.table = xtable(Fleet7_lengthsample,
                                   caption = c("Sample sizes and mean length (cm) by
                                                year for the Publicly Owned Treatment Works 
                                                trawl surveys, all Publicly Owned Treatment Works
                                               programs combined."),
                                   label = 'tab:Fleet7_lengthsample',
                                   digits=0)


print(Fleet7_lengthdepth.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})
```

\newpage

```{r, results='asis'}
print(Fleet7_lengthsample.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              scalebox=0.9)

```

\FloatBarrier
<!-- ********************************************************************** -->
<!-- **************Fleet 8 NWFSC trawl survey index TABLES***************** -->
<!-- ********************************************************************** -->


```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
      ##read in data for 3 tables
        Fleet8_catchdepth = read.csv("./txt_files/Fleet8_NWFSCTrawl_catchdepth.csv")
        Fleet8_catchlat = read.csv("./txt_files/Fleet8_NWFSCTrawl_catchlat.csv")
        Fleet8_summary = read.csv("./txt_files/Fleet8_NWFSCTrawl_summary.csv")
        Fleet8_agesummary = read.csv("./txt_files/Fleet8_NWFSCTrawl_agesummary.csv")
        Fleet8_agepercents = read.csv("./txt_files/Fleet8_NWFSCTrawl_agepercents.csv")
        Fleet8_index = read.csv("./txt_files/Fleet8_NWFSCTrawl_index.csv")
        Fleet8_meanAatL = read.csv("./txt_files/NWFSCTrawl_MeanLatA.csv")
        
        
        colnames(Fleet8_catchdepth) = c('Depth zone (m)',
                                        'Total catch (kg)',
                                        'Raw CPUE (kg/ha)')
        
        colnames(Fleet8_catchlat) = c('Latitude zone',
                                      'Total catch (kg)',
                                      'Raw CPUE (kg/ha)')
        
        colnames(Fleet8_summary) = c('Year',
                                       'No. hauls',
                                       'No. positive hauls',
                                       'Percent positive hauls',
                                       'Total catch (kg)',
                                       'Raw CPUE (kg/ha)')
          
            
        colnames(Fleet8_agesummary) = c('Year',
                                        'No. aged',
                                        'Mean age (year)',
                                        'Mean length (cm)',
                                        'No. aged',
                                        'Mean age (year)',
                                        'Mean length (cm)')
        
        colnames(Fleet8_agepercents) = c('Percentile',
                                         'Female age at percentile',
                                         'Male age at percentile')
        colnames(Fleet8_meanAatL) = c('Age',
                                      'Mean  length',
                                      'No. of Fish',
                                      'Mean length',
                                      'No. of Fish')
        
        colnames(Fleet8_index) = c('Year',
                                   'Index',
                                   'Log-scale SE')
      

```

```{r, results='asis'}
    #Fleet 8 catch by depth
        Fleet8_catchdepth.table = xtable(Fleet8_catchdepth,
                              caption = c("Summaries of catch statistics of 
                                          Califronia scorpionfish by 25 m interval depth zones 
                                          from NWFSC trawl survey between 2003 and 2016."),
                              label='tab:Fleet8_NWFSCTrawl_catchdepth')
    
        
        print(Fleet8_catchdepth.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 8 catch by latitude
         Fleet8_catchlat.table = xtable(Fleet8_catchlat,
                              caption = c("Summaries of catch statistics of 
                                          California scorpionfish by latitude zones 
                                          from NWFSC trawl survey between 2003 and 2016."),
                              label='tab:Fleet8_NWFSCTrawl_catchlat')
        
cat('\\vspace{2in}')
         
                 
        print(Fleet8_catchlat.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   
```

```{r, results='asis'}
    #Fleet 8 CPUE summary
         Fleet8_summary.table = xtable(Fleet8_summary,
                              caption = c("Summaries of haul statistics of 
                                          California scorpionfish from NWFSC 
                                          trawl survey between 2003 and 2016."),
                              label='tab:Fleet8_NWFSCTrawl_summary')
        
       align(Fleet8_summary.table) = c('l','l', rep('>{\\centering}p{.7in}', dim(Fleet8_summary)[2]-1))
        
        print(Fleet8_summary.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})  
        
        
  #Fleet 8 CPUE age summary
        Fleet8_agesummary.table = xtable(Fleet8_agesummary,
                              caption = c("Summary statistics of age data by
                                          year and sex from NWFSC trawl survey 
                                          between 2005 and 2016.  The last row
                                          shows total numbers of fish aged by sex."),
                              label='tab:Fleet8_NWFSCTrawl_agesummary',
                              digits=0)
        
        align(Fleet8_agesummary.table) = c('l',
                                           'l', 
                                           'c',
                                           '>{\\centering}p{.7in}',
                                           '>{\\centering}p{.9in}',
                                           '|c',
                                           '>{\\centering}p{.7in}',
                                           '>{\\centering}p{.9in}')
       
            addtorow <- list()
            addtorow$pos <- list()
            addtorow$pos[[1]] <- -1
            addtorow$command <- c('&  \\multicolumn{3}{c}{Female} 
                                   &  \\multicolumn{3}{c}{Male} \\\\\n')
        
          
        print(Fleet8_agesummary.table,
              add.to.row=addtorow,
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x},
              hline.after=c(-1,0,nrow(Fleet8_agesummary.table)))       
```

```{r, results='asis'}       
   #Fleet 8 CPUE age summary
         Fleet8_agepercents.table = xtable(Fleet8_agepercents,
                              caption = c("Ages at five percentiles by sex from 
                                          NWFSC trawl survey between 2005 and 2016, 
                                          indicating more older males in the population."),
                              label='tab:Fleet8_NWFSCTrawl_agepercents',
                              digits=0)
        
        
        print(Fleet8_agepercents.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})        
        
        
 #Fleet 8 mean age at length        
      Fleet8_meanAatL.table =  xtable(Fleet8_meanAatL,
                                      caption = c('Mean age-at-length (cm) and number of 
                                                    fish aged by sex for 
                                                    California scorpionfish from the NWFSC
                                                      trawl survey.'),
                                label='tab:Fleet8_NWFSCTrawl_meanAatL',
                                digits=0)
        
            addtorow <- list()
            addtorow$pos <- list()
            addtorow$pos[[1]] <- -1
            addtorow$command <- c('&  \\multicolumn{2}{c}{Female} 
                                   &  \\multicolumn{2}{c}{Male} \\\\\n')
 
      print(Fleet8_meanAatL.table, 
            add.to.row=addtorow,
            include.rownames=FALSE, 
            caption.placement="top",
            sanitize.text.function = function(x){x},
            hline.after=c(-1,0,nrow(Fleet8_meanAatL.table))) 
        
      #Fleet 8 index
         Fleet8_index.table = xtable(Fleet8_index,
                              caption = c("The NWFSC trawl survey
                                            index."),
                              digits=4,
                              label='tab:Fleet8_NWFSCTrawl_index')
        
        
        print(Fleet8_index.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})
```


\FloatBarrier
<!-- ********************************************************************** -->
<!-- ***************Fleet 9 Gillnet survey index TABLES******************** -->
<!-- ********************************************************************** -->

```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
      ##read in data for 3 tables
        Fleet9_filter = read.csv("./txt_files/Fleet9_GillnetSurvey_filter.csv")
        Fleet9_aic = read.csv("./txt_files/Fleet9_GillnetSurvey_aic.csv")
        Fleet9_index = read.csv("./txt_files/Fleet9_GillnetSurvey_index.csv")
        
        colnames(Fleet9_filter) = c('Filter',
                                    'Criteria',
                                    'Sample size (no. positive trips)',
                                    'Sample size (no. of trips)')
        
        colnames(Fleet9_aic) = c('Model',
                                 'Binomial',
                                 'Lognormal')
        
        colnames(Fleet9_index) = c('Year',
                                   'Index',
                                   'Log-scale SE')
      

```

```{r, results='asis'}
    #Fleet 9 filter
         Fleet9_filter.table = xtable(Fleet9_filter,
                              caption = c("Recreational private mode dockside data sample 
                                          sizes at each data filtering step.  
                                          The bold value indicates the final sample size 
                                          used for delta-GLM analysis."),
                              label='tab:Fleet9_GillnetSurvey_filter')
        
        align(Fleet9_filter.table) = c('l',
                                  '>{\\raggedright}p{1.5in}',
                                  '>{\\raggedright}p{2.6in}',
                                  '>{\\raggedright}p{1in}',
                                  '>{\\raggedright}p{1in}')          
 cat('\\vspace{2in}')       
        print(Fleet9_filter.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 9 aic
         Fleet9_aic.table = xtable(Fleet9_aic,
                              caption = c("AIC values for each model in the
                                          recreational private mode dockside sample 
                                          index."),
                              label='tab:Fleet9_GillnetSurvey_aic')
        
cat('\\vspace{2in}')        
        print(Fleet9_aic.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 9 index
         Fleet9_index.table = xtable(Fleet9_index,
                              caption = c("The recreational private mode 
                                            dockside sample index."),
                              digits=0,
                              label='tab:Fleet9_GillnetSurvey_index')
        
cat('\\vspace{2in}')        
        print(Fleet9_index.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})
```
\FloatBarrier
<!-- ********************************************************************** -->
<!-- ***************Fleet 11 Bight trawl survey index TABLES*************** -->
<!-- ********************************************************************** -->

```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
      ##read in data for 3 tables
        Fleet11_filter = read.csv("./txt_files/Fleet11_SCBSurvey_filter.csv")
        Fleet11_aic = read.csv("./txt_files/Fleet11_SCBSurvey_aic.csv")
        Fleet11_index = read.csv("./txt_files/Fleet11_SCBSurvey_index.csv")
        
        colnames(Fleet11_filter) = c('Filter',
                                    'Criteria',
                                    'Sample size (no. positive trips)',
                                    'Sample size (no. of trips)')
        
        colnames(Fleet11_aic) = c('Model',
                                 'Binomial',
                                 'Lognormal')
        
        colnames(Fleet11_index) = c('Year',
                                   'Index',
                                   'Log-scale SE')
      

```

```{r, results='asis'}
    #Fleet 11 filter
         Fleet11_filter.table = xtable(Fleet11_filter,
                              caption = c("Southern California Bight regional 
                                          monitoring trawl survey data sample 
                                          sizes at each data filtering step.  
                                          The bold value indicates the final sample size 
                                          used for delta-GLM analysis."),
                              label='tab:Fleet11_SCBSurvey_filter')
        
        align(Fleet11_filter.table) = c('l',
                                  '>{\\raggedright}p{1.5in}',
                                  '>{\\raggedright}p{2.6in}',
                                  '>{\\raggedright}p{1in}',
                                  '>{\\raggedright}p{1in}')          
cat('\\vspace{2in}')        
        print(Fleet11_filter.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 11 aic
         Fleet11_aic.table = xtable(Fleet11_aic,
                              caption = c("AIC values for each model in the
                                          Southern California Bight regional 
                                          monitoring trawl survey sample 
                                          index."),
                              label='tab:Fleet11_SCBSurvey_aic')
        
        
        print(Fleet11_aic.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})

   #Fleet 11 index
         Fleet11_index.table = xtable(Fleet11_index,
                              caption = c("Southern California Bight regional 
                                          monitoring trawl survey sample index."),
                              digits=4,
                              label='tab:Fleet11_SCBSurvey_index')
        
        
        print(Fleet11_index.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})
```


<!-- ********************************************************************** -->
<!-- ***************Ages by sex TABLES************************************* -->
<!-- ********************************************************************** -->

```{r, results='asis'}
      Age_by_sex = read.csv('./txt_files/Age_by_sex.csv')

      sex_ratio.table = xtable(Age_by_sex,
                          caption = c("Number of fish by sex and age from the NWFSC trawl survey"),
                             label = 'tab:sex_ratio')

      print(sex_ratio.table, 
              include.rownames=FALSE, 
              caption.placement="top")
```
